export const Types = {
    SHOW_ADD_TODO_MODAL:"SHOW_ADD_EVENT_MODAL",
    HIDE_ADD_TODO_MODAL:"HIDE_ADD_EVENT_MODAL",
    TODO_DATA:"TODO_DATA",
    ADD_TODO:"ADD_TODO",
    GET_TODO:"GET_TODO",
    UPDATE_TODO:"UPDATE_TODO",
    REORDER_TODO:"REORDER_TODO"
};
