export const Types = {
    SET_SIGN_IN_MESSAGE: "SET_SIGN_IN_MESSAGE",
    LOG_IN_USER: "LOG_IN_USER",
    REDIRECT:"REDIRECT",
    REGISTER_USER:'REGISTER_USER',
    SET_REGISTER_IN_MESSAGE:"SET_REGISTER_IN_MESSAGE"
  };
  
